/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;


import controlador.CtrlRegistrarEstudiantes;
import java.awt.event.KeyEvent;

public class FrmRegistrar extends javax.swing.JFrame {
   
     CtrlRegistrarEstudiantes ObjCtrlRegistrarEstudiantes;
     
    public FrmRegistrar() {
        initComponents();
        this.ObjCtrlRegistrarEstudiantes= new CtrlRegistrarEstudiantes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JblNumControl = new javax.swing.JLabel();
        JblNombre = new javax.swing.JLabel();
        JblCarrera = new javax.swing.JLabel();
        JblPromedio = new javax.swing.JLabel();
        BtnRegistrar = new javax.swing.JButton();
        BtnListar = new javax.swing.JButton();
        TxtPromedio = new javax.swing.JTextField();
        TxtCarrera = new javax.swing.JTextField();
        TxtNombre = new javax.swing.JTextField();
        TxtNumControl = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JblNumControl.setText("Num. Control:");
        jPanel1.add(JblNumControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        JblNombre.setText("Nombre:");
        jPanel1.add(JblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        JblCarrera.setText("Carrera:");
        jPanel1.add(JblCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        JblPromedio.setText("Promedio:");
        jPanel1.add(JblPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        BtnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarEstudiante.png"))); // NOI18N
        BtnRegistrar.setText("Guardar");
        BtnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnRegistrarMouseClicked(evt);
            }
        });
        jPanel1.add(BtnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 152, 88));

        BtnListar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ListarEstudiante.png"))); // NOI18N
        BtnListar.setText("Listar");
        BtnListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnListarMouseClicked(evt);
            }
        });
        jPanel1.add(BtnListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 160, 90));
        jPanel1.add(TxtPromedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 205, -1));
        jPanel1.add(TxtCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 205, -1));
        jPanel1.add(TxtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 204, -1));
        jPanel1.add(TxtNumControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 204, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(153, 255, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("1. Registro de estudiantes ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   private void guardarRegistro(){

       //mi controlador toma estos estos  
        ObjCtrlRegistrarEstudiantes.registrarEstudiante(
        TxtNumControl.getText(),
        TxtNombre.getText(),
        TxtCarrera.getText(),
        Double.parseDouble(TxtPromedio.getText())
    );

        
    limpiarCajas();
}
    
    private void BtnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnRegistrarMouseClicked
        // TODO add your handling code here:}
        this.guardarRegistro();
       
    }//GEN-LAST:event_BtnRegistrarMouseClicked

    private void BtnListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnListarMouseClicked
        // TODO add your handling code here:
        FrmListar ObjListar = new FrmListar();
        ObjListar.setVisible(true);
    }//GEN-LAST:event_BtnListarMouseClicked

     private void txtNumControlKeyPressed(java.awt.event.KeyEvent evt) {                                         
        // TODO add your handling code here:
        if(evt.getKeyCode()== KeyEvent.VK_ENTER )                
            this.TxtNombre.requestFocus();
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRegistrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmRegistrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnListar;
    private javax.swing.JButton BtnRegistrar;
    private javax.swing.JLabel JblCarrera;
    private javax.swing.JLabel JblNombre;
    private javax.swing.JLabel JblNumControl;
    private javax.swing.JLabel JblPromedio;
    private javax.swing.JTextField TxtCarrera;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JTextField TxtNumControl;
    private javax.swing.JTextField TxtPromedio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void limpiarCajas() {
        this.TxtNumControl.setText("");
        this.TxtNombre.setText("");
        this.TxtCarrera.setText("");
        this.TxtPromedio.setText("");
    }
}

